modLoader = "javafml"
loaderVersion = "[38,)"
license = "MIT"

[[mods]]
modId = "toolbox"
version = "${version}"
displayName = "Lazurite Toolbox"
authors = "Lazurite Team"
description = "Tools and extras used for Lazurite mods."
logoFile = "icon.png"

[[dependencies.toolbox]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolbox]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"