modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="toolbox"
version="${version}"
displayName="Lazurite Toolbox" 
logoFile="icon.png" 
credits="Lazurite team who made original Toolbox" 
authors="The Lazurite Team"
description="A set of utils used by several Lazurite mods."
[[dependencies.toolbox]] 
    modId="forge" 
    mandatory=true 
    versionRange="[37,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.toolbox]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"

# {
#   "schemaVersion": 1,
#   "id": "toolbox",
#   "version": "${version}",
#
#   "name": "Lazurite Toolbox",
#   "description": "A set of utils used by several Lazurite mods.",
#   "authors": [ "The Lazurite Team" ],
#   "contact": {
#     "homepage": "https://lazurite.dev",
#     "sources": "https://github.com/lazuritemc/lazurite-toolbox",
#     "issues": "https://github.com/lazuritemc/lazurite-toolbox/issues"
#   },
#
#   "license": "MIT",
#   "icon": "icon.png",
#   "environment": "*",
#   "mixins": [ "toolbox.mixins.json" ],
#
#   "depends": {
#     "fabricloader": ">=0.11",
#     "fabric": "*",
#     "minecraft": "1.18.x"
#   },
#
#   "suggests": {
#     "flamingo": "*"
#   }
# }
